services:
  mysql:
    image: mysql:5.7
    container_name: prestashop_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    ports:
      - '3307:3306'
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-padmin']
      interval: 10s
      timeout: 5s
      retries: 5

  prestashop:
    image: prestashop/prestashop:1.7.8.11
    container_name: prestashop
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '8081:80'
    environment:
      DB_SERVER: prestashop_mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DEV_MODE: 1
      PS_DOMAIN: host.docker.internal:8081
    networks:
      - prestashop_network
    volumes:
      - psdata:/var/www/html
    healthcheck:
      disable: true
      test: [ 'CMD', 'wget', '-q', '--spider', 'http://localhost:80' ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  tests:
    build: .
    container_name: prestashop_tests
    depends_on:
      prestashop:
        condition: service_started
    environment:
        - URL=http://host.docker.internal:8081
        - BROWSER=chrome
        - HEADED=true
        - DISPLAY=:99
    networks:
      - prestashop_network
    volumes:
      - ./tests_selenium:/app/tests_selenium
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./screenshots:/app/screenshots
    entrypoint: ['pytest']
    command: ['tests_selenium/tests/', '-v', '--browser=chrome', '--url=http://host.docker.internal:8081']

networks:
  prestashop_network:
    driver: bridge

volumes:
  dbdata:
  psdata: