FROM jenkins/jenkins:lts-jdk21

USER root

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    wget \
    unzip \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --break-system-packages \
    pytest \
    pytest-xdist \
    allure-pytest \
    selenium \
    requests \
    python-dotenv \
    faker \
    webdriver-manager

RUN wget -q https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.zip && \
    unzip -q allure-2.24.1.zip && \
    mv allure-2.24.1 /opt/allure && \
    rm allure-2.24.1.zip && \
    ln -s /opt/allure/bin/allure /usr/local/bin/allure


RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*

USER jenkins

RUN jenkins-plugin-cli --plugins \
    git \
    pipeline-stage-view \
    allure-jenkins-plugin \
    docker-workflow \
    workflow-aggregator